theme: minima
title: Musings of a Madman
author: Joel Pike
email: pikejt@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Joel Pike is a reformed Hospitality professional currently pursuing a new career in Tech.
# social links
twitter_username: JoelTPike # DO NOT include the @ character, or else the build will fail!
github_username:  JoelTPike # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

